- hosts: all
  sudo: True
  tasks:
    - name: ensure required packages are installed
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - git

